### ISSUE TITLE
Add a page in our website with Table 3

### ISSUE THREAD

**Issue by miguelgondu** [MachineLearningLifeScience/hdbo_benchmark#12]
We currently have the table available in our project's Notion page.

It would be ideal to have this as a resource online that could be easily updated when new papers come out. Would it be feasible to create a page in our website that is similar to [*What's the score?*](https://scorebasedgenerativemodeling.github.io/).

**Comment by miguelgondu** [comment]
Short title: related work
Longer title: A review of high-dimensional Bayesian optimization

**Comment by miguelgondu** [comment]
- [ ] Miguel: send Euguene a `csv` with all the info.

**Comment by eugene** [comment]
Please review the first version https://machinelearninglifescience.github.io/hdbo_benchmark/related_work/
